FlyBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: FlyBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
        takeofTime:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: FlyBundle\Entity\Terrain
            inversedBy: departures
        arrival:
            targetEntity: FlyBundle\Entity\Terrain
            inversedBy: arrivals
        plane:
            targetEntity: FlyBundle\Entity\PlaneModel
            inversedBy: model
    oneToMany:
        flights:
            targetEntity: FlyBundle\Entity\Reservation
            mappedBy: flight